apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: revolut
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: revolut
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80